# Generated by Django 5.1.6 on 2025-02-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='enrolled_at',
            new_name='enrollment_date',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='completed',
            new_name='is_completed',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='progress',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='completed_modules',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
