# Generated by Django 5.1.6 on 2025-03-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_payment_payment_method_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='uuid',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
