# Generated by Django 5.1.6 on 2025-03-03 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category_type', models.CharField(choices=[('technical', 'Technical'), ('career', 'Career'), ('research', 'Research')], max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='resources/categories/')),
            ],
            options={
                'verbose_name_plural': 'Resource Categories',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='resources/files/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Document'), ('code', 'Code'), ('other', 'Other')], max_length=10)),
                ('file_size', models.CharField(max_length=20)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resourcecategory')),
            ],
        ),
    ]
