# Generated by Django 5.1.6 on 2025-05-22 16:40

import django.contrib.postgres.search
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name='resourcecategory',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='resources/categories/'),
        ),
        migrations.AlterField(
            model_name='resourcecategory',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
